### PR TITLE
Laravel 5 support

### PR DESCRIPTION
**Pull request by AntoineAugusti**
- Laravel 5 support
- Rely on the configuration repository contract to read configuration values
- Inject the configuration repository in the service provider
- Follow new coding conventions
- Update the README file
- Add extra information in the configuration file

### CODE REVIEW

**Comment by AntoineAugusti** [comment]
Travis was failing because we now should require PHP 5.4

**Comment by uibar** [comment]
@thomaswelton please add this PR.

**Comment by Kovah** [comment]
+1

**Comment by mattstauffer** [comment]
@thomaswelton Do you intend to continue to maintain this package? If not, I'd suggest marking it as deprecated so someone else can pick it up.

**Comment by thomaswelton** [comment]
@AntoineAugusti I should now be staying on top of the maintenance of this and my other packages. However if not, and in appreciation of your contributions I have made you a collaborator on this repo.
Thanks.

**Pull request merged**
