### PR TITLE
Updated to support Laravel 8.x

### PR DESCRIPTION
**Pull request by daikazu**

### CODE REVIEW

**Review by sebastienheyd — APPROVED** [review]

**Review by wells — APPROVED** [review]

**Comment by sebastienheyd** [comment]
14 days to approve a PR that just add 8.0 to the supported Laravel versions, is this project dead ?

**Comment by thomaswelton** [comment]
> 14 days to approve a PR that just add 8.0 to the supported Laravel versions, is this project dead ?

I'm not actively maintaining it, nor do I use this package in any of the projects I'm currently building.
Thanks @AntoineAugusti for picking this up.

If there is anyone else that want to maintain this project that'd be welcomed.

**Comment by AntoineAugusti** [comment]
Hey folks,

Building on what @thomaswelton said, it's ok to remind maintainers to merge PRs when it's been a few weeks, just be thoughtful. We're all busy bees and Thomas and I are not using this project at the moment.

Thanks for submitting a PR @sebastienheyd and sorry for delaying this release.

Hope everyone has a nice weekend.

**Comment by sebastienheyd** [comment]
@thomaswelton if needed, I can help you to maintain this package, I'm actively using it in one of mine [sebastienheyd/boilerplate](https://github.com/sebastienheyd/boilerplate).

**Pull request merged**
